baseURL = "https://dinnyfonseca.github.io"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Dinny Fonseca"
theme = "dream"

enableRobotsTXT = true
disqusShortname = "dinnyfonseca"

copyright = 'Todos os direitos reservados'
googleAnalytics = "UA-153647691-4"

# Paginate = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# https://g1eny0ung.site/hugo-theme-dream/#/params-configurations
[params]
  # background = "black"
  backgroundImage = "/wallpaper.jpg"
  # options from css: no-repeat, repeat, repeat-x or repeat-y
  backgroundImageRepeat = "repeat"
  linkColor = "seagreen"

  author = "Dinny Fonseca"
  description = "descrição aqui"
  avatar = "/me/avatar_fb.jpg"
  motto = "sub-titulo aqui"
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  utterancesRepo = "dinnyfonseca/dinnyfonseca.github.io"
  
  email = "dinnyariadne@gmail.com"
  twitter = "ariadneassis"
  facebook = "ariadne.assis"
  instagram = "dinnyassis"
  youtube = "dinnyfonseca"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
